### ISSUE TITLE
update to react 15.5

### ISSUE THREAD

**Issue by Pomax** [Pomax/react-formbuilder#24]
- classes
- refactor proptypes

/cc @mmmavis in case you're interested in helping on this one =)

**Comment by mmmavis** [comment]
Hey @Pomax I'm gonna be traveling + PTO till first week of May. If this is not needed in 2 weeks I can definitely work on a PR for it. 😁

**Comment by Pomax** [comment]
I think we can wait a little bit =)

**Comment by mmmavis** [comment]
Will get to this next week.

**Comment by mmmavis** [comment]
I've finally started working on this. Will file a PR and tag you for review when it's ready!
