### ISSUE TITLE
More descriptive documentation for `controller`

### ISSUE THREAD

**Issue by mmmavis** [Pomax/react-formbuilder#29]
README has some documentation about `controller` but it can probably be more descriptive and detailed.

**Comment by Pomax** [comment]
what level of detail are you looking for?

**Comment by mmmavis** [comment]
@Pomax I think the current doc is good as is. For some reason I didn't get it when I first read it... I added `controller` to the same field object and that's why it didn't work for me

e.g.,
```js
'somefieldname': {
    type: `choiceGroup`,
    label: `Would you like to deliver this session bilingually in one of the following languages?`,
    options: [
      `Spanish`,
      `German`,
      `French`,
      `Other`
    ],
    controller: {
      name: `somefieldname`,
      value: `Other`
    }
  }
```

**Comment by Pomax** [comment]
Ah. I'll close this for now then.
