### ISSUE TITLE
Automatically import react when required

### ISSUE THREAD

**Issue by arush0311** [Pomax/react-formbuilder#36]
JSX requires react to be present in the scope, but it is not imported here https://github.com/Pomax/react-formbuilder/blob/master/src/fields/CheckBoxGroup.jsx#L1
So it complains during render.

**Comment by Pomax** [comment]
This should not be solved by explicitly importing React, but by making the build tool do the right thing. What is the actual error you get? Let's try to find the proper solution to fixing this based on the description in that error.

**Comment by arush0311** [comment]
Okay i its make more sense to use an automatic react importer using http://webpack.github.io/docs/list-of-plugins.html#provideplugin
