### ISSUE TITLE
Allow more input types

### ISSUE THREAD

**Issue by mmmavis** [Pomax/react-formbuilder#6]
It seems like the form builder currently only accepts the following input types 
```
type: ["text"|"textarea"|"choiceGroup"|"checkbox"|"checkboxGroup"|ReactComponent]
```
Types like `email`, `url`, `submit`... etc should also be allowed.

**Comment by Pomax** [comment]
email is text, so that's a matter of passing in the right validator. Same for url. A submit is *not* going to happen because the form should, under no circumstance, ever automatically submit. You *must* run through the validation rules, and a submit button bypasses that.
